version: "3"

services:

  runtime-setup:
    image: swift-service-context:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"


  test:
    image: swift-service-context:22.04-main
    environment:
      #- SANITIZER_ARG=--sanitize=thread
      - FORCE_TEST_DISCOVERY=--enable-test-discovery
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: swift-service-context:22.04-main
