version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing-baggage:20.04-5.5
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.5"

  test:
    image: swift-distributed-tracing-baggage:20.04-5.5
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-distributed-tracing-baggage:20.04-5.5
