version: "3"

services:

  runtime-setup:
    image: swift-service-context:20.04-5.6
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.6"

  test:
    image: swift-service-context:20.04-5.6
    environment:
      #- SANITIZER_ARG=--sanitize=thread
      - FORCE_TEST_DISCOVERY=--enable-test-discovery

  shell:
    image: swift-service-context:20.04-5.6
