//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift Context Propagation open source project
//
// Copyright (c) 2020 Apple Inc. and the Swift Baggage Context project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// LoggingBaggageContextCarrierTests+XCTest.swift
//
import XCTest
///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension LoggingBaggageContextCarrierTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (LoggingBaggageContextCarrierTests) -> () throws -> Void)] {
      return [
                ("test_ContextWithLogger_dumpBaggage", test_ContextWithLogger_dumpBaggage),
                ("test_ContextWithLogger_log_withBaggage", test_ContextWithLogger_log_withBaggage),
           ]
   }
}

